spring:
  application:
    name: Continuous Online Hearing
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    database: postgresql
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cor}
    username: ${SPRING_DATASOURCE_USERNAME:cor}
    password: ${SPRING_DATASOURCE_PASSWORD:cor}
    tomcat:
      max-active: ${MAX_ACTIVE_DB_CONNECTIONS:50} # Maximum number of active connections that can be allocated from this pool at the same time.
      max-idle: ${MAX_IDLE_DB_CONNECTIONS:25}
      max-wait: ${MAX_WAIT_DB_CONNECTIONS:10000} # Number of ms to wait before throwing an exception if no connection is available.
      test-on-borrow: ${TEST_ON_BORROW_DB_CONNECTION:true} # Validate the connection before borrowing it from the pool.
    type: com.zaxxer.hikari.HikariDataSource
      hikari:
        auto-commit: false
  liquibase:
   enabled: false
   change-log: classpath:/db/changelog/db.changelog-master.yam

base-urls:
  idam-url: ${IDAM_API_URL:http://localhost:4501}
  idam-user-email: ${IDAM_USER_EMAIL:test-citizen22@example.com}
  idam-user-role: ${IDAM_API_USER_ROLE:citizen}
  test-url: ${TEST_URL:http://localhost:8080}

deadline:
  extension-days: 7

scheduling:
  enabled: false
  lock_at_most_for: ${SCHEDULING_LOCK_AT_MOST_FOR:PT10M} # 10 minutes in ISO-8601

event-scheduler:
    event-notifier:
      fixed-delay: 360000
    event-trigger:
      fixed-delay: 360000
      cron: 0 0 1 * * ?

#this need to be removed
info:
  app:
    environment: ${PACKAGES_ENVIRONMENT:local}
    project: ${PACKAGES_PROJECT:coh}
    name: ${PACKAGES_NAME:cor}

azure:
  app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:true}
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:dummy}

aat:
  test-notification-endpoint: ${base-urls.test-url}/SSCS/notifications

idam:
  s2s-auth:
    url: ${S2S_URL:http://localhost:4502}
    microservice: ${TEST_S2S_SERVICE:em_gw}
    totp_secret: ${TEST_S2S_TOKEN:AAAAAAAAAAAAAAAA}

test:
  client_name: webshow
  client_secret: ${FUNCTIONAL_TEST_CLIENT_OAUTH_SECRET:AAAAAAAAAAAAAAAA}
  client_redirect: ${IDAM_WEBSHOW_WHITELIST:http://localhost:8080/oauth2redirect}
